language: node_js

node_js:
  - lts/*

cache:
  yarn: true
  directories:
    - "node_modules"

before_install:
  - curl -LO http://gosspublic.alicdn.com/ossutil/1.6.7/ossutil64
  - chmod +x ossutil64
  - ./ossutil64 config -e $ENDPOINT -i $ACCESS_KEY_ID -k $ACCESS_KEY_SECRET

install:
  - yarn install

script:
  - npm run docs:build

after_success:
- ./ossutil64 cp -rf docs/.vuepress/dist oss://zulu-wang